version: '3'
volumes:
  database-data:
services:
  database:
    container_name: postgres
    image: "library/postgres:16.1-alpine"
    environment:
      - POSTGRES_DB=overdose
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=America/SaoPaulo
      - PGTZ=America/SaoPaulo
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  flyway:
    container_name: flyway
    image: "flyway/flyway"
    command: -configFiles=flyway.conf migrate -X
    volumes:
      - database-data:/var/lib/flyway/data/
      - ./conf/flyway.conf:/flyway/flyway.conf
      - .:/flyway/sql
    depends_on:
      - database